version: '3.8'
services:
  db:
    image: postgres:latest

    restart: always
    environment:
      POSTGRES_USER: youruser  # Choisis un user, e.g., 'admin'
      POSTGRES_PASSWORD: yourpassword  # Choisis un mot de passe fort
      POSTGRES_DB: meetingdb  # Nom de ta DB
    ports:
      - "5432:5432"
    volumes:
      # IMPORTANT: mount to /var/lib/postgresql (not /data)
      - db-data:/var/lib/postgresql


volumes:
  db-data: